import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/DasComponent/Navbar/Navbar";
import Footer from "@/DasComponent/Others/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-bgLight"}>
        <div className="flex">
          <div className="bg-bgDark min-h-screen">
            <Navbar />
          </div>
          <div className="w-full mt-[65px]">
            <div>{children}</div>
            <div>
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
