import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/DasComponent/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className+" bg-bgLight"}>
        <div className="flex">
          <div className="bg-bgDark min-h-screen">
            <Navbar />
          </div>
          <div className="w-full mt-[65px]">{children}</div>
          {/* <Image src={"/images/logo.png"} className='h-[50px]' width={200} height={100} alt='Logo'/> */}
        </div>
      </body>
    </html>
  );
}
